version: '3'
services:
  mongodb:
    image: mongo:5
    container_name: mongodb
    ports: 
      - 27017:27017
    restart: always
  backend:
    build: ./backend
    container_name: habit_backend
    environment:
      - API_PORT=4000
      - MONGO_URL=mongodb://mongodb:27017/habits
      - TOKEN_KEY="TOKENHABIT"
    ports:
      - 4000:4000
    depends_on:
      - mongodb
  frontend:
    build: ./frontend/habits
    container_name: habit_frontend
    ports:
      - 3000:3000